config {
  type: "view",
  database: "focused-sentry-464713-u0",
  schema: "clio_johnson", 
  name: "stg_johnson_clio", 
  tags: ["clio", "matters", "contacts", "bruce law"]
}

/*
  Changelog: yyyy-mm-dd jbatoy: 
*/

WITH cte_contacts AS (
  SELECT
    CASE
      WHEN Primary_Email = 'nan' AND Primary_Phone = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), LOWER(First), LOWER(Last))
      WHEN Primary_Email = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), REGEXP_REPLACE(Primary_Phone, r"^'", ""))
      WHEN Primary_Phone = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), REGEXP_REPLACE(Primary_Email, r"^'", ""))
    ELSE CONCAT(PARSE_DATE('%m/%d/%Y', Created), REGEXP_REPLACE(Primary_Email, r"^'", "")) END AS c_custom_id
    , PARSE_DATE('%m/%d/%Y', Created) AS c_created
    , IF(Contact_Global_ID = 'nan', NULL, Contact_Global_ID) AS c_contact_global_id
    , IF(First = 'nan', NULL, First) AS c_first
    , IF(Middle = 'nan', NULL, Middle) AS c_middle
    , IF(Last = 'nan', NULL, Last) AS c_last
    , IF(Date_of_Birth = 'nan', NULL, Date_of_Birth) AS c_date_of_birth
    , IF(Company_Name = 'nan', NULL, Company_Name) AS c_company_name
    , IF(Primary_Email = 'nan', NULL, Primary_Email) AS c_primary_email
    , IF(Home_Email = 'nan', NULL, Home_Email) AS c_home_email
    , IF(Work_Email = 'nan', NULL, Work_Email) AS c_work_email
    , IF(Other_Email = 'nan', NULL, Other_Email) AS c_other_email
    , IF(Primary_Phone = 'nan', NULL, Primary_Phone) AS c_primary_phone
    , IF(Home_Phone = 'nan', NULL, Home_Phone) AS c_home_phone 
    , IF(Mobile_Phone = 'nan', NULL, Mobile_Phone) AS c_mobile_phone
    , IF(Work_Phone = 'nan', NULL, Work_Phone) AS c_work_phone
    , IF(Street = 'nan', NULL, Street) AS c_street
    , IF(City = 'nan', NULL, City) AS c_city
    , IF(State = 'nan', NULL, State) AS c_state
    , IF(Country = 'nan', NULL, Country) AS c_country
    , IF(Zipcode = 'nan', NULL, Zipcode) AS c_zipcode
    , IF(Source = 'nan', NULL, Source) AS c_source
    , IF(Status = 'nan', NULL, Status) AS c_status
    , IF(Client_Status = 'nan', NULL, Client_Status) AS c_client_status
    , IF(URL = 'nan', NULL, URL) AS c_url
    , IF(Tags = 'nan', NULL, Tags) AS c_tags
    , IF(Referred_By = 'nan', NULL, Referred_By) AS c_referred_by
    , IF(Name_of_the_assigned_attorney__ = 'nan', NULL, Name_of_the_assigned_attorney__) AS c_name_of_the_assigned_attorney
    , IF(Referred_by_ = 'nan', NULL, Referred_by_) AS c_referred_by_
    , IF(effortlesslegal_id = 'nan', NULL, effortlesslegal_id) AS c_effortlesslegal_id
  FROM `focused-sentry-464713-u0.clio_johnson.manual_contacts`
)

, cte_matters AS (
  SELECT
    CASE
      WHEN Client_Email = 'nan' AND Client_Phone_Number = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), LOWER(First_Name), LOWER(Last_Name))
      WHEN Client_Email = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), Client_Phone_Number)
      WHEN Client_Phone_Number = 'nan' THEN CONCAT(PARSE_DATE('%m/%d/%Y', Created), Client_Email)
    ELSE CONCAT(PARSE_DATE('%m/%d/%Y', Created), Client_Email) END AS m_custom_id
    , PARSE_DATE('%m/%d/%Y', Created) AS m_created
    , IF(Matter_Type = 'nan', NULL, Matter_Type) AS m_matter_type
    , IF(Status = 'nan', NULL, Status) AS m_status
    , IF(Location = 'nan', NULL, Location) AS m_location
    , IF(Assigned_To = 'nan', NULL, Assigned_To) AS m_assigned_to
    , IF(Created_By = 'nan', NULL, Created_By) AS m_created_by
    , IF(Description = 'nan', NULL, Description) AS m_description
    , IF(Value = 'nan', NULL, Value) AS m_value
    , IF(Client = 'nan', NULL, Client) AS m_client
    , IF(Client_Contact_Type = 'nan', NULL, Client_Contact_Type) AS m_client_contact_type
    , IF(Client_Status = 'nan', NULL, Client_Status) AS m_client_status
    , IF(Client_Source = 'nan', NULL, Client_Source) AS m_client_source
    , IF(First_Name = 'nan', NULL, First_Name) AS m_first_name
    , IF(Last_Name = 'nan', NULL, Last_Name) AS m_last_name
    , IF(Client_Email = 'nan', NULL, Client_Email) AS m_client_email
    , IF(Client_Phone_Number = 'nan', NULL, Client_Phone_Number) AS m_client_phone_number
    , IF(Client_Street = 'nan', NULL, Client_Street) AS m_client_street
    , IF(Client_City = 'nan', NULL, Client_City) AS m_client_city
    , IF(Client_State = 'nan', NULL, Client_State) AS m_client_state
    , IF(Client_Zip = 'nan', NULL, Client_Zip) AS m_client_zip
    , IF(Other_Contacts = 'nan', NULL, Other_Contacts) AS m_other_contacts
    , IF(Referred_By = 'nan', NULL, Referred_By) AS m_referred_by
    , IF(Matter_Source_1 = 'nan', NULL, Matter_Source_1) AS m_matter_source_1
    , IF(Matter_Source_2 = 'nan', NULL, Matter_Source_2) AS m_matter_source_2
    , IF(_001_Another_Name_ = 'nan', NULL, _001_Another_Name_) AS m_001_another_name
    , IF(_003_Do_you_have_an_attorney_ = 'nan', NULL, _003_Do_you_have_an_attorney_) AS m_003_do_you_have_an_attorney
    , IF(_006_County = 'nan', NULL, _006_County) AS m_006_county
    , IF(_007_Case_Number = 'nan', NULL, _007_Case_Number) AS m_007_case_number
    , IF(_012_Name_of_Opposing_Party = 'nan', NULL, _012_Name_of_Opposing_Party) AS m_012_name_of_opposing_party
    , IF(_1st_Missed_Consult_Date = 'nan', NULL, _1st_Missed_Consult_Date) AS m_1st_missed_consult_date
    , IF(_2nd_Missed_Consultation_Date = 'nan', NULL, _2nd_Missed_Consultation_Date) AS m_2nd_missed_consultation_date
    , IF(Active_or_Inactive_ = 'nan', NULL, Active_or_Inactive_) AS m_active_or_inactive
    , IF(Ad_Group = 'nan', NULL, Ad_Group) AS m_ad_group
    , IF(Agreement_Type = 'nan', NULL, Agreement_Type) AS m_agreement_type
    , IF(Appointment_Set_By = 'nan', NULL, Appointment_Set_By) AS m_appointment_set_by
    , IF(Attorney_Consult = 'nan', NULL, Attorney_Consult) AS m_attorney_consult
    , IF(Attorney_assigned_to_case_ = 'nan', NULL, Attorney_assigned_to_case_) AS m_attorney_assigned_to_case
    , IF(Auto_Pay_ = 'nan', NULL, Auto_Pay_) AS m_auto_pay
    , IF(BILLING_NOTES__PLEASE_READ__ = 'nan', NULL, BILLING_NOTES__PLEASE_READ__) AS m_billing_notes_please_read
    , IF(Client_Referred_by_JLG_Employee_ = 'nan', NULL, Client_Referred_by_JLG_Employee_) AS m_client_referred_by_jlg_employee
    , IF(Collections_Rate = 'nan', NULL, Collections_Rate) AS m_collections_rate
    , IF(Contact_Preference = 'nan', NULL, Contact_Preference) AS m_contact_preference
    , IF(Criminal_Law = 'nan', NULL, Criminal_Law) AS m_criminal_law
    , IF(Current_Location__City__State_ = 'nan', NULL, Current_Location__City__State_) AS m_current_location_city_state
    , IF(Discount_or_No_Discount_ = 'nan', NULL, Discount_or_No_Discount_) AS m_discount_or_no_discount
    , IF(Have_you_heard_our_commercial_on_the_radio_ = 'nan', NULL, Have_you_heard_our_commercial_on_the_radio_) AS m_have_you_heard_our_commercial_on_the_radio
    , IF(Have_you_seen_our_billboards_ = 'nan', NULL, Have_you_seen_our_billboards_) AS m_have_you_seen_our_billboards
    , IF(Hearing__Trial__Mediation_Date__ = 'nan', NULL, Hearing__Trial__Mediation_Date__) AS m_hearing_trial_mediation_date
    , IF(Hired_Date = 'nan', NULL, Hired_Date) AS m_hired_date
    , IF(Immigration_Law = 'nan', NULL, Immigration_Law) AS m_immigration_law
    , IF(Initial_Contact_Method = 'nan', NULL, Initial_Contact_Method) AS m_initial_contact_method
    , IF(Initial_Contact_Time = 'nan', NULL, Initial_Contact_Time) AS m_initial_contact_time
    , IF(Intake_Date = 'nan', NULL, Intake_Date) AS m_intake_date
    , IF(Keap = 'nan', NULL, Keap) AS m_keap
    , IF(Keywords = 'nan', NULL, Keywords) AS m_keywords
    , IF(Language = 'nan', NULL, Language) AS m_language
    , IF(Legal_Professional_Consult_With = 'nan', NULL, Legal_Professional_Consult_With) AS m_legal_professional_consult_with
    , IF(Legal_Professional_Intake_Date = 'nan', NULL, Legal_Professional_Intake_Date) AS m_legal_professional_intake_date
    , IF(Limited_or_Full_Representation_ = 'nan', NULL, Limited_or_Full_Representation_) AS m_limited_or_full_representation
    , IF(Location_Payment_Made = 'nan', NULL, Location_Payment_Made) AS m_location_payment_made
    , IF(Looking_to_hire_an_Atty_ = 'nan', NULL, Looking_to_hire_an_Atty_) AS m_looking_to_hire_an_atty
    , IF(Marketing_Campaign = 'nan', NULL, Marketing_Campaign) AS m_marketing_campaign
    , IF(Notes_on_Collections_Rate = 'nan', NULL, Notes_on_Collections_Rate) AS m_notes_on_collections_rate
    , IF(OP_previous_law_firm = 'nan', NULL, OP_previous_law_firm) AS m_op_previous_law_firm
    , IF(PC_previous_law_firm = 'nan', NULL, PC_previous_law_firm) AS m_pc_previous_law_firm
    , IF(Paid_Atty_Consultation_Date = 'nan', NULL, Paid_Atty_Consultation_Date) AS m_paid_atty_consultation_date
    , IF(Payment_form_ = 'nan', NULL, Payment_form_) AS m_payment_form
    , IF(Primary_Language = 'nan', NULL, Primary_Language) AS m_primary_language
    , IF(Pronouns__if_selected_ = 'nan', NULL, Pronouns__if_selected_) AS m_pronouns_if_selected
    , IF(Rescheduled_Set_Date = 'nan', NULL, Rescheduled_Set_Date) AS m_rescheduled_set_date
    , IF(Retainer_Amount = 'nan', NULL, Retainer_Amount) AS m_retainer_amount
    , IF(Retainer_Type = 'nan', NULL, Retainer_Type) AS m_retainer_type
    , IF(SMS_Opt_In = 'nan', NULL, SMS_Opt_In) AS m_sms_opt_in
    , IF(Scheduled_Initial_Consultation_Date = 'nan', NULL, Scheduled_Initial_Consultation_Date) AS m_scheduled_initial_consultation_date
    , IF(Second_Consult_Date = 'nan', NULL, Second_Consult_Date) AS m_second_consult_date
    , IF(Second_Set_By = 'nan', NULL, Second_Set_By) AS m_second_set_by
    , IF(Set_Date = 'nan', NULL, Set_Date) AS m_set_date
    , IF(Term_Searched = 'nan', NULL, Term_Searched) AS m_term_searched
    , IF(Third_Consult_Date = 'nan', NULL, Third_Consult_Date) AS m_third_consult_date
    , IF(Type_of_Intake_Appointment = 'nan', NULL, Type_of_Intake_Appointment) AS m_type_of_intake_appointment
    , IF(Waiver_of_AC_Privilege_ = 'nan', NULL, Waiver_of_AC_Privilege_) AS m_waiver_of_ac_privilege
    , IF(Yearly_Income = 'nan', NULL, Yearly_Income) AS m_yearly_income
  FROM `focused-sentry-464713-u0.clio_johnson.manual_matters`
)

SELECT DISTINCT
    c.*
    , m.*
FROM cte_contacts c
LEFT JOIN cte_matters m ON c.c_custom_id = m.m_custom_id
