config {
  type: "table",
  database: "focused-sentry-464713-u0",
  schema: "clio_bruce", 
  name: "src_bl_clio_contacts", 
  tags: ["external", "gcs", "contacts", "bruce law"]
}

/*
  Changelog: yyyy-mm-dd jbatoy: 
*/

pre_operations {
CREATE EXTERNAL TABLE IF NOT EXISTS focused-sentry-464713-u0.clio_bruce.ext_bl_clio_contacts (
    created                                                             STRING
    , contact_global_id                                                 STRING
    , first                                                             STRING
    , middle                                                            STRING
    , last                                                              STRING
    , date_of_birth     	                                            STRING
    , company_name                                                      STRING
    , primary_email                                                     STRING	
    , home_email                                                        STRING
    , work_email                                                        STRING
    , other_email                                                       STRING
    , primary_phone                                                     STRING
    , home_phone                                                        STRING
    , mobile_phone                                                      STRING
    , work_phone                                                        STRING
    , street            	                                            STRING
    , city                                                              STRING
    , state                                                             STRING
    , country                                                           STRING
    , zipcode                                                           STRING
    , source                                                            STRING
    , status            	                                            STRING
    , client_status     	                                            STRING
    , url                                                               STRING
    , tags	                                                            STRING
    , referred_by                                                       STRING
    , communication_preference                                          STRING
    , dob                                                               STRING
    , date_of_birth_1                                                   STRING
    , date_of_intake_call                                               STRING
    , drivers_license_number                                            STRING
    , employed	                                                        STRING
    , gender	                                                        STRING
    , intake_approximate_length_of_intake_call_minutes                  STRING
    , intake_date_of_consultation	                                    STRING
    , intake_description_of_call_notes                                  STRING
    , intake_name_of_lawyer_the_pnc_requested_to_meet	                STRING
    , intake_name_of_person_calling_the_firm	                        STRING
    , intake_time_of_day_of_consultation_if_scheduled                   STRING
    , intake_as_a_follow_up_message_sent	                            STRING
    , intake_name_of_referral_source	                                STRING
    , intake_notes_from_intake_call                                     STRING
    , intake_was_a_consultation_scheduled                               STRING
    , intake_did_pnc_set_consultation                                   STRING
    , lead_type                                                         STRING
    , location_of_consultation_if_consultation_was_scheduled_only       STRING
    , marital_status	                                                STRING
    , means_to_pay                                                      STRING
    , name_of_person_calling_the_firm	                                STRING
    , name_of_team_member_handling_intake_call	                        STRING
    , opposing_party_first_and_last_name	                            STRING
    , please_provide_the_first_and_last_name_of_any_parties_involved_with_this_matter_opposing_party STRING
    , preferred_contact_method                                          STRING
    , pronoun_his_her_their                	                            STRING
    , referral_source	                                                STRING
    , ssn_last_four                                                     STRING
    , social_security_number                                            STRING	
    , weblead	                                                        STRING	
    , what_county_does_this_matter_reside_in	                        STRING
    , gclid                                                             STRING
    , utm_campaign                                                      STRING
    , utm_content                                                       STRING
    , utm_medium	                                                    STRING
    , utm_source                                                        STRING
    , utm_term                                                          STRING
)
OPTIONS (
  format = 'CSV',
  field_delimiter = '\t',
  skip_leading_rows = 1,
  uris = ['gs://gcs-clio-bruce/manual/contacts/*.csv']
)
}

SELECT _file_name as file_name
    ,  created                                                            
    , contact_global_id                                                
    , first                                                            
    , middle                                                           
    , last                                                             
    , date_of_birth     	                                           
    , company_name                                                     
    , primary_email                                                    
    , home_email                                                       
    , work_email                                                       
    , other_email                                                      
    , primary_phone                                                    
    , home_phone                                                       
    , mobile_phone                                                     
    , work_phone                                                       
    , street            	                                           
    , city                                                             
    , state                                                            
    , country                                                          
    , zipcode                                                          
    , source                                                           
    , status            	                                           
    , client_status     	                                           
    , url                                                              
    , tags	                                                           
    , referred_by                                                      
    , communication_preference                                         
    , dob                                                              
    , date_of_birth_1                                                  
    , date_of_intake_call                                              
    , drivers_license_number                                           
    , employed	                                                       
    , gender	                                                       
    , intake_approximate_length_of_intake_call_minutes                 
    , intake_date_of_consultation	                                   
    , intake_description_of_call_notes                                 
    , intake_name_of_lawyer_the_pnc_requested_to_meet	               
    , intake_name_of_person_calling_the_firm	                       
    , intake_time_of_day_of_consultation_if_scheduled                  
    , intake_as_a_follow_up_message_sent	                           
    , intake_name_of_referral_source	                               
    , intake_notes_from_intake_call                                    
    , intake_was_a_consultation_scheduled                              
    , intake_did_pnc_set_consultation                                  
    , lead_type                                                        
    , location_of_consultation_if_consultation_was_scheduled_only      
    , marital_status	                                               
    , means_to_pay                                                     
    , name_of_person_calling_the_firm	                               
    , name_of_team_member_handling_intake_call	                       
    , opposing_party_first_and_last_name
    , please_provide_the_first_and_last_name_of_any_parties_involved_with_this_matter_opposing_party
    , preferred_contact_method                 
    , pronoun_his_her_their                	   
    , referral_source	                       
    , ssn_last_four                            
    , social_security_number                   
    , weblead	                               
    , what_county_does_this_matter_reside_in	
    , gclid                                    
    , utm_campaign                             
    , utm_content                              
    , utm_medium	                           
    , utm_source                               
    , utm_term                                 	                           
FROM `focused-sentry-464713-u0.clio_bruce.ext_bl_clio_contacts`
${ when(incremental(), `WHERE _file_name NOT IN (SELECT DISTINCT _file_name FROM ${self()})`) }
